version: '3.8'

services:
  backend:
    build:
      context: ./tax_clustering
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./tax_clustering:/backend
      - ./media:/media  # Монтируем директорию media
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
